sudo: false
language: node_js
cache:
  npm: true
notifications:
  email: true
node_js:
  - '12'
before_script:
  - npm prune
script:
  - npm run lint
  - npm test
  - npm run ban -f
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
